build:
	docker buildx build --platform linux/amd64 -t europe-docker.pkg.dev/amazemind/amazemind-services/scula-smm:0.1 .

push:
	docker push europe-docker.pkg.dev/amazemind/amazemind-services/scula-smm:0.1